### ISSUE TITLE
How many games did it play to get this result?

### ISSUE THREAD

**Issue by ClownW** [rdenadai/snakeplissken#3]
Hey, I'm using you repo to train my snake. However, I'm wondering how many games did it play to get you result? It have trained for 15000 games but it only eats 2 apples per game at most.

**Comment by rdenadai** [comment]
Hi @ClownW, i don't know exactly how many games it played... im running again from scratch to see if there's some bug in my code that prevents you from achieve the results i have.
One thing i should say is that, a run more than once from scratch the snake, saving the model each time... this was important because after a while the snake will stop explore, but the state space for the game is huge... so running again from scratch, cleaning it memory was a need in my case...

Also, another important fact that i did, was periodically run the snake in "overfitting model", which is calling the **train.py** code... in this code, the snake will not explore the space, but instead will train only on the memories that recorded... i find this another important step... 

The problem in running only the main.py is that you have no warranty that the good memories (when the snake eat the apple) will ever be process... that's because we get random memories from the ReplayMemorie... sure there's a change, but.........................

So, i'm running again from scratch and will report back...

Also, keep in mind... for me to achieve the result took me lot's of days of trial and error and lot's of GPU cycles!!!

**Comment by ClownW** [comment]
Thanks a lot! I will try your tips of cleaning it memory and running the train.py code. I never thought of that before. And also being patient to train.

**Comment by rdenadai** [comment]
I'm running again from scratch as a said... as off now i'm getting some close to 8 to 10 apples... soon i'll report back all of the steps done.

But i run a mixed of scripts... run main.py for a period, and then train.py... repeat the process 5 times, close to 1500 games and 464k iterations!

**Comment by ClownW** [comment]
One thing still puzzles me that if cleaning the memory is necessary. The ReplayMemory class is defined when the memory is full, the new trace will cover the old. 

So do I need to clean the memory?

**Comment by rdenadai** [comment]
Not necessary... i find good to clean up the memory some times just to make sure that the network learn from a new empty one with better approximations... specially if you run the train.py.

Think that way... you collected lots of random shitty states (the snake running around doing nothing)... then you run the train.py to make the snake NN weights "overfitting" this data... so the snake improves a little bit... if you did not clean up... eventually the same data already seen will be show again (you want that for the "good & bad memories" as i called, but not for the short one, which is the snake just circling around the map.

Anyway... it's not needed it to reset the memory, but if did that... from time to time... do that if the good and or bad memories are full and after runned the train.py a few times (like 2-3x)!!!

**Comment by rdenadai** [comment]
Another important aspact... is the a new memory (using the **main.py**) has no warranty of being seen by the snake... specially if your memory pool is really huge!

**Comment by ClownW** [comment]
Thank you for your suggestions. After change the way it choose action back and run train.py, my snake performs much better than before. I'll try to repeat this process a few more times and hope to achieve your results.

**Comment by rdenadai** [comment]
Great to hear! As i said... it took lot's of time to achieve the results... as i running again from scratch, the snake is now performing like 10-13 apples... but i'm been running for almost 2 days now... but i'm running in a more restricted environment (low FPS, memory and image size)...

**Comment by ClownW** [comment]
After training for a few days, my snake can eat 6~9 apples now. However, it still looks quite stupid now because it would always circle around the map before the position of the apple change. So do you have some experience about this?

**Comment by rdenadai** [comment]
One thing you can do to try speed up the performance... is clean up the memory and change the config **APPLE_RELOAD_STEPS**... this way the apple will appear more faster, making the state space change more faster too.
